### ISSUE TITLE
Missing texture for the Slimefun Guide

### ISSUE THREAD

**Issue by orcachillin** [54M44R/Slimefun-Beautified#1]
![image](https://user-images.githubusercontent.com/61361654/137171609-9ddf64a8-7a61-45e5-adae-71023471dbed.png)

Pack list:
![image](https://user-images.githubusercontent.com/61361654/137171711-3fecfefc-9470-42a2-a761-6de39a3fd953.png)

**Comment by 54M44R** [comment]
The json file referring to the texture for the Slimefun Guide was referencing a dark version which does not exist. This issue has been solved
