### ISSUE TITLE
Texture issue in 1.19.3

### ISSUE THREAD

**Issue by UltraPuPower** [54M44R/Slimefun-Beautified#6]
Hey 54M44R,
I am currently working on a mc client for 1.19.3, and I want to use the Sf beautified texture pack. However it seems very glitched. As you can see all textures are just squares, I have custom textures working, this is also visible in one of the screenshots where you can see some extra enchanted books. The mod used to see the SF items in the guide on the side is compatible with the Sf beautified pack,  or atleast it was in 1.19.2.
![2023-02-17_17 14 29](https://user-images.githubusercontent.com/122467778/219706655-d96b91a3-4d15-4c62-b243-6619a67b2fb4.png)
![2023-02-17_17 14 31](https://user-images.githubusercontent.com/122467778/219706660-4c92b369-b105-4774-a0f8-3dee4de9a2b9.png)
![2023-02-17_17 14 33](https://user-images.githubusercontent.com/122467778/219706662-28f092ce-fb32-49b8-8545-63c4a4e8316c.png)
![2023-02-17_17 14 36](https://user-images.githubusercontent.com/122467778/219706665-190a06bb-43ca-46d5-8e07-0cd0e67f99c0.png)

**Comment by 54M44R** [comment]
I'm sorry I never handled this far sooner, but the issue was regarding the introduction of the way that the Minecraft texture atlas works in 1.19.3

This has been fixed on the latest release
